#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Prooph\ServiceBus\CommandBus;

\Boot\SocialNetwork::create();
$container = \Boot\SocialNetwork::getContainer();
\Boot\SocialNetwork::router($container, $commandBus = new CommandBus());
\Boot\SocialNetwork::console($container, $commandBus);
