version: '3'
services:
  worker:
    build: ./DockerFiles/Worker
    ports:
      - ${LOCAL_IP}:${SOCIAL_NETWORK_SERVER_PORT}:81
      - ${LOCAL_IP}:${PHP_SSH_PORT}:22
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      SOCIAL_NETWORK_MYSQL_HOST: mysql
      SOCIAL_NETWORK_MYSQL_DATABASE: alireza
      SOCIAL_NETWORK_MYSQL_USER: root
      SOCIAL_NETWORK_MYSQL_PASSWORD: root
      SOCIAL_NETWORK_MYSQL_PORT: 3306
      LOCAL_DEV_DIR: ${LOCAL_DEV_DIR}
      VENDOR_DIR: ${VENDOR_DIR}
    volumes:
      - ${LOCAL_DEV_DIR}:/var/www
      - ${LOCAL_DEV_DIR}/storage:/var/www/storage
  mysql:
    build: ./DockerFiles/Mysql
    ports:
      - ${LOCAL_IP}:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
