version: '3'
services:
  worker:
    build: ./DockerFiles/Worker
    ports:
    - ${LOCAL_IP}:${PHP_SSH_PORT}:22
    depends_on:
    - mysql
    - memcached
    links:
    - mysql
    - memcached
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: socialnetwork
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      LOCAL_DIR: ${LOCAL_DIR}
    volumes:
    - ${LOCAL_DIR}:/var/www
  mysql:
    build: ./DockerFiles/Mysql
    ports:
    - ${LOCAL_IP}:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  memcached:
    build: ./DockerFiles/Memcached