<?php
namespace Test;

use InvalidArgumentException;
use RuntimeException;
use SocialNetwork\Infrastructure\Cli\AddPostCli;
use Symfony\Component\Console\Tester\CommandTester;

class AddPostCliTest extends SocialNetwork
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        \Mockery::close();
    }

    /** @test */
    public function should_throw_exception_with_less_argument()
    {
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Not enough arguments (missing: "username, sign").');
        $command = new CommandTester(new AddPostCli($this->commandBus, $this->container));
        $command->execute(['message' => 'hi there']);
    }

    /** @test */
    public function should_throw_exception_with_more_argument()
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('The "more-argument" argument does not exist.');
        $command = new CommandTester(new AddPostCli($this->commandBus, $this->container));
        $command->execute(['message' => 'hi there', 'sign' => 'hi there ' , 'more-argument' => 'this is more']);
    }

    /** @test */
    public function should_display_well_done_in_console()
    {
        $this->commandBus->shouldReceive('dispatch')->times(1)->andReturnNull();
        $command = new CommandTester(new AddPostCli($this->commandBus, $this->container));
        $command->execute(['username' => 'testguy', 'sign' => 'hi there', 'message' => 'hi there']);
        $this->assertEquals($command->getDisplay(),' posted to wall of testguy successfully 
' );
    }
}
