<?php
namespace Test;

use SocialNetwork\Domain\Aggregates\TimelineAggregate;
use SocialNetwork\Infrastructure\Repositories\Persistence\TimelineRepository as PTR;

class PersistenceTimelineRepositoryTest extends SocialNetwork
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        \Mockery::close();
    }

    /** @test */
    public function should_save_aggregate()
    {
        /** @var PTR $repository */
        $repository = $this->container->get(PTR::class);
        $aggregate = TimelineAggregate::addPost('test-username', 'test-message');
        $repository->save($aggregate);
        $this->assertEquals($aggregate, $repository->get($aggregate->getId()));
    }
}
