<?php
namespace Test;

use Mockery;
use Prooph\ServiceBus\CommandBus;
use Prooph\ServiceBus\Plugin\Router\CommandRouter;
use SocialNetwork\Application\Services\TimeService;
use SocialNetwork\Infrastructure\Cli\Output\TimelineCliOutput;
use Symfony\Component\DependencyInjection\Container;

abstract class SocialNetwork extends \PHPUnit\Framework\TestCase
{
    /** @var TimelineCliOutput */
    protected $timelineCli;

    /** @var TimeService */
    protected $timeService;

    /** @var CommandBus */
    protected $commandBus;

    /** @var CommandRouter */
    protected $router;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->timelineCli = new TimelineCliOutput();
        $this->timeService = Mockery::mock(TimeService::class);
        $this->commandBus = Mockery::mock(CommandBus::class);
        $this->router = Mockery::mock(CommandRouter::class);
    }

    public function getContainer(): Container
    {
        return \Boot\SocialNetwork::create(\Boot\SocialNetwork::TEST)::getContainer();
    }
}
