<?php
namespace Test;

use Prooph\ServiceBus\CommandBus;
use Prooph\ServiceBus\Plugin\Router\CommandRouter;
use SocialNetwork\Application\Services\TimeService;
use SocialNetwork\Infrastructure\Cli\Output\TimelineCliOutput;
use Symfony\Component\DependencyInjection\Container;

abstract class SocialNetwork extends \PHPUnit\Framework\TestCase
{
    /** @var TimelineCliOutput */
    protected $timelineCli;

    /** @var TimeService */
    protected $timeService;

    /** @var CommandBus */
    protected $commandBus;

    /** @var CommandRouter */
    protected $router;

    /** @var \MyCachedContainerTest */
    protected $container;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->container = $this->getContainer();
        $this->timelineCli = new TimelineCliOutput();
        $this->timeService = new TimeService();
        $this->commandBus = \Mockery::mock(CommandBus::class);
        $this->router = new CommandRouter();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        \Mockery::close();
    }

    public function getContainer(): Container
    {
        \Boot\SocialNetwork::create(\Boot\SocialNetwork::TEST);
        return \Boot\SocialNetwork::getContainer();
    }
}
