<?php
namespace Test;

class TimelineCliOutputTest extends SocialNetwork
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        \Mockery::close();
    }

    /** @test */
    public function should_throw_exception_with_empty_result()
    {
        $this->expectException(\Assert\AssertionFailedException::class);
        $this->expectExceptionMessage('sorry, result is not valid');
        $this->timelineCli->success([], $this->timeService);
    }
}
