<?php
namespace Test;

use InvalidArgumentException;
use RuntimeException;
use SocialNetwork\Infrastructure\Cli\ReadCli;
use SocialNetwork\Infrastructure\Cli\WallCli;
use Symfony\Component\Console\Tester\CommandTester;

class WallCliTest extends SocialNetwork
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function should_throw_exception_with_less_argument()
    {
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Not enough arguments (missing: "username").');
        $command = new CommandTester(new WallCli($this->commandBus, $this->container));
        $command->execute([]);
    }

    /** @test */
    public function should_throw_exception_with_undefined_argument()
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('The "message" argument does not exist.');
        $command = new CommandTester(new WallCli($this->commandBus, $this->container));
        $command->execute(['message' => 'hi there']);
    }
}
