mysql:
  prod:
    uri: mysql:host=mysql;port=3306;dbname=my_social_network_prod
    user: root
    pass: root
  test:
    uri: mysql:host=mysql;port=3306;dbname=my_social_network_test
    user: root
    pass: root